[package]
name = "advent2020"
version = "0.1.0"
authors = ["Eugene Korbut <me@mvl.ru>"]
edition = "2018"

[[bin]]
name = 'day01'
path = 'src/day01/main.rs'

[[bin]]
name = 'day02'
path = 'src/day02/main.rs'

[dependencies]
regex = "1"
lazy_static= "1"
